# Generated by Django 3.2.5 on 2021-08-01 16:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=255)),
                ('driverCityOrigin', models.CharField(max_length=255)),
                ('driverLanguage', models.CharField(max_length=255)),
                ('driverPhone', models.CharField(max_length=255)),
                ('driverInfo', models.CharField(max_length=255)),
                ('licensePlate', models.CharField(max_length=255)),
                ('kmDriven', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
